apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  labels:
    name: fluentd
    project: devops
spec:
  project: devops
  source:
    repoURL: "https://git.example.com/devops/kubernetes-manifest.git"
    targetRevision: HEAD
    path: devops/fluentd/overlays/dev
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated: {}
