stages:
  - test

default:
  image: asia-southeast2-docker.pkg.dev/host-cicd/docker-utils/tf:1.3.0

fmt:
  stage: test
  script:
    - ./bin/ci/fmt-checker
  artifacts:
    when: on_failure
    paths:
      - diff.patch
