apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  notifications.argoproj.io/subscribe.slack: argocd-dev-stg

resources:
- ../../base
#

# Devops application
- application/devops/argocd-project.yaml
- application/devops/datadog.yaml
- application/devops/devops-runner.yaml
- application/devops/fluentd.yaml
- application/devops/gitlab-mr-bot.yaml
- application/devops/ingress-nginx.yaml
# - application/devops/jaeger.yaml
- application/devops/opentelemetry.yaml
- application/devops/stop-start-bot.yaml
